### ISSUE TITLE
And with Handlebars ? 

### ISSUE THREAD

**Issue by Akashrine** [crucialfelix/gulp-blog-scaffold#1]
Hello hello, 

Do you have any idea how to adapt your blog task with handlebars and not jade ?
I've got an issue with this line : 

handlebarsTpl = purehandlebars.compile(tpl),  must receive a String and I'm pretty sure i'm giving him the content of my layout.hbs ...

**Comment by crucialfelix** [comment]
Sorry, I don't use handlebars and can't debug that one for you.  This repo is just a sketch to see if the idea works. Hope its useful for you !
